@rota = notes
@idUser = 1

###
# @name test
GET {{url}}/{{rota}}

###
# @name Create
POST {{url}}/{{rota}}/create
Content-Type: application/json

{
    "title": "Destinmos à Deriva",
    "description": "Grávida, sozinha e perdida no mar, uma mulher que está presa em um container tenta sobreviver após fugir de um país totalitário e destruído.",
    "rating": 3.3,
    "userId": 1
}

###
# @name ShowAll
GET {{url}}/{{rota}}/showAll

###
# @name Index
GET {{url}}/{{rota}}/1

###
# @name Delete
DELETE {{url}}/{{rota}}/3

###
# @name Update
PUT {{url}}/{{rota}}/2
Content-Type: application/json

{
    "rating": 3.3
}
